name: PHP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  cs:
    runs-on: ubuntu-latest
    name: Code Style

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run cs
      run: composer run cs

  phpstan:
    runs-on: ubuntu-latest
    name: Static Analysis

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run phpstan
      run: composer run phpstan

  phpunit:
    runs-on: ubuntu-latest
    name: Integration Tests

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: redis, pgsql

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: composer run integration
